version: '3.1'

services:

  mongo:
    image: mongo:5.0
    restart: always
    volumes:
      - ./traffic:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mps
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: traffic

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mps
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_MONGODB_URL: mongodb://mps:root@mongo:27017/